import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import type { ComponentProps } from 'react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { preloadMarkdownPreview } from './components/lazyMarkdownPreview'
import { DOCUMENT_DRAFT_STORAGE_KEY } from './domain/documentDraft'
import { RECENT_FILES_STORAGE_KEY, type RecentFile } from './domain/recentFiles'
import { OUTLINE_PREFERENCES_STORAGE_KEY } from './domain/outlinePreferences'
import type { FileAccess, OpenedMarkdownFile } from './platform/fileAccess'


describe('App', () => {
  beforeEach(async () => {
    await preloadMarkdownPreview()
    window.localStorage.clear()
    document.documentElement.removeAttribute('data-mdview-color-theme')
    document.documentElement.removeAttribute('data-mdview-font-family')
    document.documentElement.style.removeProperty('--reader-font-size')
    document.documentElement.style.removeProperty('--reader-line-height')
    document.documentElement.style.removeProperty('--reader-content-width')
    setNavigatorPlatform('Win32')
  })

  it('exports the current preview as self-contained HTML', async () => {
    const user = userEvent.setup()
    const exportHtmlFile = vi.fn<FileAccess['exportHtmlFile']>(async () => '/tmp/report.html')
    renderApp({
      fileAccess: createFileAccess({
        startupFile: file(
          '/tmp/report.md',
          ['# Exported', '', '| Key | Value |', '| --- | --- |', '| OS | Windows |', '', '```ts', 'const ready = true', '```'].join('\n'),
        ),
        exportHtmlFile,
      }),
    })

    expect(await screen.findByRole('heading', { name: 'Exported' })).toBeInTheDocument()

    await openExportMenu(user)
    await user.click(screen.getByRole('menuitem', { name: 'Export as HTML' }))

    await waitFor(() => {
      expect(exportHtmlFile).toHaveBeenCalledTimes(1)
    })
    const [html, currentPath, title] = exportHtmlFile.mock.calls[0]
    expect(currentPath).toBe('/tmp/report.md')
    expect(title).toBe('report.md')
    expect(html).toContain('<!doctype html>')
    expect(html).toContain('<html lang="en">')
    expect(html).toContain('<h1 id="exported">Exported</h1>')
    expect(html).toContain('<table>')
    expect(html).toContain('ready =')
    expect(screen.getByText('HTML exported')).toBeInTheDocument()
  })

  it('shows export canceled when HTML export is canceled', async () => {
    const user = userEvent.setup()
    renderApp({
      fileAccess: createFileAccess({
        exportHtmlFile: vi.fn(async () => null),
      }),
    })

    await openExportMenu(user)
    await user.click(screen.getByRole('menuitem', { name: 'Export as HTML' }))

    expect(await screen.findByText('Export canceled')).toBeInTheDocument()
  })

  it('shows export errors when HTML export fails', async () => {
    const user = userEvent.setup()
    renderApp({
      fileAccess: createFileAccess({
        exportHtmlFile: vi.fn(async () => {
          throw new Error('export failed')
        }),
      }),
    })

    await openExportMenu(user)
    await user.click(screen.getByRole('menuitem', { name: 'Export as HTML' }))

    expect(await screen.findByText('export failed')).toBeInTheDocument()
  })

  it('opens the print dialog for PDF export', async () => {
    const user = userEvent.setup()
    const printExportHtml = vi.fn<FileAccess['printExportHtml']>(async () => undefined)
    renderApp({
      fileAccess: createFileAccess({
        startupFile: file('/tmp/print.md', '# Printable'),
        printExportHtml,
      }),
    })

    expect(await screen.findByRole('heading', { name: 'Printable' })).toBeInTheDocument()

    await openExportMenu(user)
    await user.click(screen.getByRole('menuitem', { name: 'Export as PDF' }))

    await waitFor(() => {
      expect(printExportHtml).toHaveBeenCalledTimes(1)
    })
    const [html, title] = printExportHtml.mock.calls[0]
    expect(html).toContain('<h1 id="printable">Printable</h1>')
    expect(title).toBe('print.md')
    expect(screen.getByText('Print dialog opened')).toBeInTheDocument()
  })

  it('exports the current markdown document as DOCX', async () => {
    const user = userEvent.setup()
    let completeExport: ((path: string | null) => void) | null = null
    const exportDocxFile = vi.fn<FileAccess['exportDocxFile']>(
      () => new Promise((resolve) => {
        completeExport = resolve
      }),
    )
    renderApp({
      fileAccess: {
        ...createFileAccess({
          startupFile: file('/tmp/report.md', '# Report\n\nGenerated by **MDView**.'),
        }),
        exportDocxFile,
      } as FileAccess,
    })

    expect(await screen.findByRole('heading', { name: 'Report' })).toBeInTheDocument()

    await openExportMenu(user)
    await user.click(screen.getByRole('menuitem', { name: 'Export as Word (.docx)' }))

    await waitFor(() => {
      expect(exportDocxFile).toHaveBeenCalledTimes(1)
    })
    expect(screen.getByText('Generating Word document...')).toBeInTheDocument()
    const [bytes, currentPath, title] = exportDocxFile.mock.calls[0]
    expect(bytes).toBeInstanceOf(Uint8Array)
    expect(currentPath).toBe('/tmp/report.md')
    expect(title).toBe('report.md')

    act(() => {
      completeExport?.('/tmp/report.docx')
    })
    expect(await screen.findByText('Word exported')).toBeInTheDocument()
  })
})

function renderApp(props: ComponentProps<typeof App>) {
  const result = renderWelcomeApp(props)
  fireEvent.click(screen.getByRole('button', { name: /Create new markdown file|新建 Markdown 文件/ }))
  fireEvent.click(screen.getByRole('button', { name: /Preview markdown|预览 Markdown/ }))
  return result
}

function renderWelcomeApp(props: ComponentProps<typeof App>) {
  return render(<App {...props} initialLanguage={props.initialLanguage ?? 'en'} />)
}

async function openFileMenu(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole('button', { name: 'File' }))
}

async function openExportMenu(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole('button', { name: 'Export' }))
}

async function openAppMenu(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole('button', { name: 'App' }))
}

function file(path: string, content: string): OpenedMarkdownFile {
  return { path, content }
}

function createFileAccess(
  overrides: {
    startupFile?: OpenedMarkdownFile | null
    openFile?: OpenedMarkdownFile | null
    supportsNativeFiles?: boolean
    supportsImageImport?: boolean
    saveMarkdownFile?: FileAccess['saveMarkdownFile']
    saveMarkdownFileAs?: FileAccess['saveMarkdownFileAs']
    exportHtmlFile?: FileAccess['exportHtmlFile']
    exportDocxFile?: FileAccess['exportDocxFile']
    printExportHtml?: FileAccess['printExportHtml']
    openMarkdownFileAtPath?: FileAccess['openMarkdownFileAtPath']
    revealFileInFolder?: FileAccess['revealFileInFolder']
    readLocalImageFile?: FileAccess['readLocalImageFile']
    writeImageAsset?: FileAccess['writeImageAsset']
    listenForOpenedFiles?: FileAccess['listenForOpenedFiles']
  } = {},
): FileAccess {
  return {
    supportsNativeFiles: overrides.supportsNativeFiles ?? true,
    supportsImageImport: overrides.supportsImageImport ?? true,
    openMarkdownFile: vi.fn(async () => overrides.openFile ?? null),
    openMarkdownFileAtPath:
      overrides.openMarkdownFileAtPath ?? vi.fn(async (path) => file(path, '# Recent')),
    revealFileInFolder: overrides.revealFileInFolder ?? vi.fn(async () => undefined),
    saveMarkdownFile: overrides.saveMarkdownFile ?? vi.fn(async (path) => path),
    saveMarkdownFileAs: overrides.saveMarkdownFileAs ?? vi.fn(async () => '/tmp/saved-as.md'),
    exportHtmlFile: overrides.exportHtmlFile ?? vi.fn(async () => '/tmp/export.html'),
    exportDocxFile: overrides.exportDocxFile ?? vi.fn(async () => '/tmp/export.docx'),
    printExportHtml: overrides.printExportHtml ?? vi.fn(async () => undefined),
    readLocalImageFile:
      overrides.readLocalImageFile ??
      vi.fn(async (path) => ({ path, dataUrl: 'data:image/png;base64,test' })),
    writeImageAsset: overrides.writeImageAsset ?? vi.fn(async () => ({
      path: '/tmp/assets/image.png',
      relativePath: 'assets/image.png',
      filename: 'image.png',
    })),
    readStartupMarkdownFile: vi.fn(async () => overrides.startupFile ?? null),
    listenForOpenedFiles: overrides.listenForOpenedFiles ?? vi.fn(async () => null),
  }
}

function recent(path: string, lastOpenedAt: string): RecentFile {
  return {
    path,
    title: path.split('/').at(-1) ?? path,
    lastOpenedAt,
  }
}

function seedRecentFiles(recentFiles: RecentFile[]) {
  window.localStorage.setItem(RECENT_FILES_STORAGE_KEY, JSON.stringify(recentFiles))
}

function seedDocumentDraft(draft: Record<string, unknown>) {
  window.localStorage.setItem(DOCUMENT_DRAFT_STORAGE_KEY, JSON.stringify(draft))
}

function getStoredRecentFiles(): RecentFile[] {
  return JSON.parse(window.localStorage.getItem(RECENT_FILES_STORAGE_KEY) ?? '[]') as RecentFile[]
}

function getStoredOutlinePreferences(): Record<string, unknown> {
  return JSON.parse(window.localStorage.getItem(OUTLINE_PREFERENCES_STORAGE_KEY) ?? '{}') as Record<
    string,
    unknown
  >
}

function mockElementTop(element: Element, top: number) {
  element.getBoundingClientRect = vi.fn(() => ({
    x: 0,
    y: top,
    top,
    left: 0,
    right: 0,
    bottom: top,
    width: 0,
    height: 0,
    toJSON: () => ({}),
  }))
}

function setNavigatorPlatform(platform: string) {
  Object.defineProperty(window.navigator, 'platform', {
    configurable: true,
    value: platform,
  })
}

void openFileMenu
void openAppMenu
void recent
void seedRecentFiles
void seedDocumentDraft
void getStoredRecentFiles
void getStoredOutlinePreferences
void mockElementTop
